update lesson README.md
learn-co-curriculum/java-mod-4-optional pull request #1
Opened 2022-10-04 15:20 UTC by linda-seiter

2022-10-04 16:10 UTC, kcleland0818 requested changes
Looks great!

2022-10-04 16:10 UTC, kcleland0818 commented on README.md
>    `Null Pointer Exception` if a null value is passed to the method.
Shouldn't `Null Pointer Exception` be `NullPointerException`? Or are we just stating it could throw a null pointer exception? If it is the latter, then maybe remove the backticks.

2022-10-04 16:52 UTC, linda-seiter commented on README.md
>    `Null Pointer Exception` if a null value is passed to the method.
yes, thanks.  I'll update to NullPointerException

2022-10-04 16:54 UTC, kcleland0818 approved these changes

2022-10-12 20:07 UTC, AlveeM approved these changes

2022-10-12 20:07 UTC, merged